users:
  user:
    username: user
    articleIds: []
    commentIds: []
  other_user:
    username: user2
    articleIds: []
    commentIds: []
articles: {}
nextArticleId: 1
comments:
  '1':
    id: 1
    body: Body
    username: user
    articleId: 1
    upvotedBy: []
    downvotedBy:
      - user
nextCommentId: 1
